services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fase2-mundial-backup
    user: root
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Mundial.123
      - MSSQL_PID=Developer
    volumes:
      - ./completo:/backups/completo/
      - ./diferencial:/backups/diferencial/
